### ISSUE TITLE
It seems to expect `./rcrack` to exist but it's not part of the repo

### ISSUE THREAD

**Issue by Krutonium** [Pitasi/aax-to-mp3#3]
I'm trying to decrypt a book, but I'm running into this:

```
 ✘  ~/aax-to-mp3   master ±  python3 convert.py ./Book/InheritanceTheInheritanceCycleBook4_ep6\(1\).aax
Opening ./Book/InheritanceTheInheritanceCycleBook4_ep6(1).aax
Traceback (most recent call last):
  File "/home/krutonium/aax-to-mp3/convert.py", line 161, in <module>
    main(
  File "/home/krutonium/aax-to-mp3/convert.py", line 84, in main
    activation_bytes = get_activation_bytes(input_file=input_file)
  File "/home/krutonium/aax-to-mp3/convert.py", line 49, in get_activation_bytes
    _, stdout, _ = run_cmd(
  File "/home/krutonium/aax-to-mp3/convert.py", line 19, in run_cmd
    process = Popen(
  File "/nix/store/33hlmb4afkk7l2fapfik80m6yknjxq10-python3-3.9.12/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/33hlmb4afkk7l2fapfik80m6yknjxq10-python3-3.9.12/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: './rcrack'

```

Thoughts?

**Comment by pitasi** [comment]
Hi @Krutonium. First of all, it's been a long time since I last used this script.

This rcrack script comes from the https://github.com/inAudible-NG/tables repo, which is included as a submodule in this repo, so you should have it inside `aax-to-mp3/tables/rcrack`.

Did you clone as explained in the readme?

```
$ git clone --recurse-submodules -j8 https://github.com/Pitasi/aax-to-mp3
```

Ensure you have a non empty `aax-to-mp3/tables/` folder.

---

That said, my submodule points to a very old commit (https://github.com/inAudible-NG/tables/tree/79b000c1907da1942a44ab8e37286a7ab5b771dd), if they didn't change their API too much you also try to update it to the latest version:

```
cd aax-to-mp3/tables/
git checkout master
git pull
```

Updating might be something worth doing, since it's possible that the aax format changed in past years (I honestly don't know).

**Comment by Krutonium** [comment]
I did follow the instructions as seen in the readme - I'll double check it when I'm at my PC though.
